const fs = require('fs');
let code = fs.readFileSync('src/components/technomania/technomania-register-client.tsx', 'utf8');

const leaderOld = '<div className="grid grid-cols-1 md:grid-cols-3 gap-4">\n                <input type="text" placeholder="Full Name" required className="bg-black border border-tm-border rounded-xl p-3 text-sm text-white font-tm-mono outline-none focus:border-white" value={leader.name} onChange={e => setLeader({...leader, name: e.target.value})} />\n                <input type="email" placeholder="Email Address" required className="bg-black border border-tm-border rounded-xl p-3 text-sm text-white font-tm-mono outline-none focus:border-white" value={leader.email} onChange={e => setLeader({...leader, email: e.target.value})} />\n                <input type="text" placeholder="University UID" required className="bg-black border border-tm-border rounded-xl p-3 text-sm text-white font-tm-mono outline-none focus:border-white" value={leader.uid} onChange={e => setLeader({...leader, uid: e.target.value})} />\n              </div>';

const leaderNew = leaderOld + '\n              {selectedEvent.slug === "battlegrid" && subCategory && (\n                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">\n                  <input type="text" placeholder={subCategory === "VALORANT" ? "Riot ID" : subCategory === "CLASH ROYALE" ? "Player Tag" : "Player ID"} required className="bg-black border border-tm-border rounded-xl p-3 text-sm text-white font-tm-mono outline-none focus:border-white" value={(leader as any).gameId || ""} onChange={e => setLeader({...leader, gameId: e.target.value} as any)} />\n                  <input type="text" placeholder="In-Game Name (IGN)" required className="bg-black border border-tm-border rounded-xl p-3 text-sm text-white font-tm-mono outline-none focus:border-white" value={(leader as any).inGameName || ""} onChange={e => setLeader({...leader, inGameName: e.target.value} as any)} />\n                </div>\n              )}';

code = code.replace(leaderOld, leaderNew);

const memberOld = '<input type="text" placeholder="Full Name" required className="bg-black border border-tm-border rounded-xl p-3 text-sm text-white font-tm-mono outline-none focus:border-white" value={m.name} onChange={e => { const newM = [...members]; newM[i].name = e.target.value; setMembers(newM); }} />\n                      <input type="email" placeholder="Email Address" required className="col-span-1 md:col-span-2 bg-black border border-tm-border rounded-xl p-3 text-sm text-white font-tm-mono outline-none focus:border-white" value={m.email} onChange={e => { const newM = [...members]; newM[i].email = e.target.value; setMembers(newM); }} />\n                      <div className="flex gap-2">\n                        <input type="text" placeholder="UID" required className="flex-1 bg-black border border-tm-border rounded-xl p-3 text-sm text-white font-tm-mono outline-none focus:border-white" value={m.uid} onChange={e => { const newM = [...members]; newM[i].uid = e.target.value; setMembers(newM); }} />\n                        {true && (\n                          <button type="button" onClick={() => removeMember(i)} className="w-12 flex items-center justify-center text-tm-dim hover:text-red-500 transition-colors bg-black border border-tm-border rounded-xl">\n                            <AlertCircle size={16} />\n                          </button>\n                        )}\n                      </div>';

const memberNew = '<div className="grid grid-cols-1 md:grid-cols-4 gap-4 w-full md:col-span-4">\n' + memberOld + '\n</div>\n                      {selectedEvent.slug === "battlegrid" && subCategory && (\n                        <div className="col-span-1 md:col-span-4 grid grid-cols-1 md:grid-cols-2 gap-4">\n                          <input type="text" placeholder={subCategory === "VALORANT" ? "Riot ID" : subCategory === "CLASH ROYALE" ? "Player Tag" : "Player ID"} required className="bg-black border border-tm-border rounded-xl p-3 text-sm text-white font-tm-mono outline-none focus:border-white" value={(m as any).gameId || ""} onChange={e => { const newM: any = [...members]; newM[i].gameId = e.target.value; setMembers(newM); }} />\n                          <input type="text" placeholder="In-Game Name (IGN)" required className="bg-black border border-tm-border rounded-xl p-3 text-sm text-white font-tm-mono outline-none focus:border-white" value={(m as any).inGameName || ""} onChange={e => { const newM: any = [...members]; newM[i].inGameName = e.target.value; setMembers(newM); }} />\n                        </div>\n                      )}';

code = code.replace(memberOld, memberNew);

fs.writeFileSync('src/components/technomania/technomania-register-client.tsx', code);
