import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

type CertificateStudent = {
  uid?: string;
  name: string;
  program?: string;
  semester?: number;
};

type CertificateSheet = {
  clubName?: string;
  logo?: string;
  eventName: string;
  date: string;
  type: "participation" | "winner";
  students: CertificateStudent[];
  secretaryName?: string;
  facultyName?: string;
};

const pageSize: [number, number] = [841.89, 595.28];
const violet = rgb(0.36, 0.2, 0.82);
const magenta = rgb(0.86, 0.18, 0.68);
const ink = rgb(0.08, 0.07, 0.12);
const muted = rgb(0.38, 0.36, 0.43);

function center(page: any, font: any, text: string, y: number, size: number, color = ink) {
  const width = font.widthOfTextAtSize(text, size);
  page.drawText(text, { x: (pageSize[0] - width) / 2, y, size, font, color });
}

function fit(font: any, value: string, size: number, maxWidth: number) {
  let text = value || "";
  while (text.length && font.widthOfTextAtSize(text, size) > maxWidth) text = text.slice(0, -1);
  return text.length < value.length ? `${text.slice(0, -1)}.` : text;
}

async function embedLogo(pdf: PDFDocument, logo?: string) {
  if (!logo) return null;
  try {
    const response = await fetch(logo, { cache: "no-store" });
    if (!response.ok) return null;
    const bytes = new Uint8Array(await response.arrayBuffer());
    const lower = logo.toLowerCase();
    if (lower.includes(".jpg") || lower.includes(".jpeg")) return await pdf.embedJpg(bytes);
    return await pdf.embedPng(bytes);
  } catch {
    return null;
  }
}

function drawCertificate(page: any, fonts: { regular: any; bold: any; italic: any }, student: CertificateStudent, sheet: CertificateSheet, logo: any) {
  const { regular, bold, italic } = fonts;
  page.drawRectangle({ x: 0, y: 0, width: pageSize[0], height: pageSize[1], color: rgb(0.985, 0.98, 1) });

  page.drawRectangle({ x: 28, y: 28, width: pageSize[0] - 56, height: pageSize[1] - 56, borderWidth: 2.2, borderColor: violet });
  page.drawRectangle({ x: 42, y: 42, width: pageSize[0] - 84, height: pageSize[1] - 84, borderWidth: 0.8, borderColor: magenta });

  page.drawCircle({ x: 104, y: 492, size: 96, color: rgb(0.88, 0.82, 1), opacity: 0.22 });
  page.drawCircle({ x: 744, y: 98, size: 130, color: rgb(0.96, 0.64, 0.88), opacity: 0.2 });
  page.drawLine({ start: { x: 78, y: 122 }, end: { x: 764, y: 472 }, thickness: 1.3, color: rgb(0.64, 0.48, 0.95), opacity: 0.28 });
  page.drawLine({ start: { x: 120, y: 92 }, end: { x: 720, y: 504 }, thickness: 0.7, color: rgb(0.9, 0.36, 0.78), opacity: 0.22 });

  if (logo) {
    const scaled = logo.scale(0.18);
    const width = Math.min(74, scaled.width);
    const height = scaled.height * (width / scaled.width);
    page.drawImage(logo, { x: (pageSize[0] - width) / 2, y: 482, width, height });
  }

  center(page, bold, String(sheet.clubName || "TECH TATVA").toUpperCase(), 450, 18, violet);
  center(page, regular, sheet.type === "winner" ? "CERTIFICATE OF ACHIEVEMENT" : "CERTIFICATE OF PARTICIPATION", 410, 34, ink);
  center(page, italic, "This certificate is proudly presented to", 366, 15, muted);

  center(page, bold, fit(bold, student.name, 42, 620), 314, 42, ink);
  page.drawLine({ start: { x: 210, y: 302 }, end: { x: 632, y: 302 }, thickness: 1, color: rgb(0.7, 0.62, 0.86) });

  const action = sheet.type === "winner" ? "for outstanding performance in" : "for active participation in";
  center(page, regular, action, 264, 16, muted);
  center(page, bold, fit(bold, sheet.eventName, 24, 620), 226, 24, violet);

  const meta = [student.uid ? `UID: ${student.uid}` : "", student.program || "", student.semester ? `Semester ${student.semester}` : ""].filter(Boolean).join("  |  ");
  if (meta) center(page, regular, meta, 190, 11, muted);
  if (sheet.date) center(page, regular, `Date: ${sheet.date}`, 168, 11, muted);

  page.drawLine({ start: { x: 116, y: 112 }, end: { x: 286, y: 112 }, thickness: 0.8, color: ink });
  page.drawLine({ start: { x: 556, y: 112 }, end: { x: 726, y: 112 }, thickness: 0.8, color: ink });
  center(page, regular, sheet.secretaryName || "Secretary", 92, 11, muted);
  page.drawText(sheet.facultyName || "Faculty Champion", { x: 595 - (regular.widthOfTextAtSize(sheet.facultyName || "Faculty Champion", 11) / 2), y: 92, size: 11, font: regular, color: muted });

  center(page, regular, "Generated by Tech Tatva OS", 60, 9, rgb(0.5, 0.46, 0.56));
}

export async function certificatePdf(sheet: CertificateSheet) {
  const pdf = await PDFDocument.create();
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const italic = await pdf.embedFont(StandardFonts.HelveticaOblique);
  const logo = await embedLogo(pdf, sheet.logo);
  const students = sheet.students.length ? sheet.students : [{ name: "No present candidates" }];

  students.forEach((student) => {
    const page = pdf.addPage(pageSize);
    drawCertificate(page, { regular, bold, italic }, student, sheet, logo);
  });

  return Buffer.from(await pdf.save());
}
