import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, CalendarDays, ChevronRight, Orbit, Sparkles, Zap } from "lucide-react";
import { EventCard } from "@/components/event-card";
import { PublicShell } from "@/components/public-shell";
import { Reveal } from "@/components/reveal";
import { getPublicHomeData } from "@/lib/public-data";

export const dynamic = "force-dynamic";

const SectionTitle = ({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) => <div className="mb-10 max-w-2xl"><p className="mb-4 text-[10px] font-semibold tracking-[.3em] text-violet-300">{eyebrow}</p><h2 className="text-3xl font-medium tracking-tight md:text-5xl">{title}</h2>{copy&&<p className="mt-4 text-sm leading-7 text-white/45">{copy}</p>}</div>;
const EmptyState = ({ title, copy, href, action }: { title: string; copy: string; href?: string; action?: string }) => <div className="edge rounded-2xl bg-white/[.025] p-8 text-center"><p className="text-sm text-white/70">{title}</p><p className="mx-auto mt-3 max-w-md text-xs leading-6 text-white/40">{copy}</p>{href&&action?<Link className="mt-5 inline-flex rounded-full border border-violet-300/20 px-5 py-2 text-xs text-violet-200" href={href}>{action}</Link>:null}</div>;

export default async function Home() {
  const { clubInfo, events, teams, achievements, sponsors, gallery, stats } = await getPublicHomeData();
  const statRows = [
    [String(stats.members), "Active members"],
    [String(stats.events), "Published events"],
    [String(stats.teams), "Active teams"],
    [String(achievements.length), "Featured achievements"]
  ];
  return <PublicShell>
    <section className="relative min-h-[900px] overflow-hidden pt-20"><Image src="/tech-tatva-hero.png" alt="" fill priority className="object-cover object-center opacity-70"/><div className="absolute inset-0 bg-gradient-to-b from-black/20 via-black/25 to-ink"/><div className="absolute inset-0 grid-bg opacity-20"/>
      <div className="relative mx-auto flex min-h-[780px] max-w-7xl items-center px-6"><div className="max-w-3xl pt-16"><Reveal><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-violet-300/20 bg-violet-500/10 px-4 py-2 text-[10px] font-bold tracking-[.22em] text-violet-200"><Sparkles size={13}/> THE OPERATING SYSTEM FOR BUILDERS</div><h1 className="gradient-text text-6xl font-medium leading-[.94] tracking-[-.075em] md:text-8xl lg:text-[112px]">Ideas become<br/>inevitable.</h1><p className="mt-8 max-w-xl text-base leading-7 text-white/55">Tech Tatva is where ambitious students design, engineer, launch, and lead. One connected platform for the people making the next thing real.</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/events" className="flex items-center gap-2 rounded-full bg-white px-6 py-3 text-sm font-semibold text-black transition hover:bg-violet-100">Explore events <ArrowRight size={16}/></Link><Link href="/about" className="flex items-center gap-2 rounded-full border border-white/15 bg-black/20 px-6 py-3 text-sm text-white/75 backdrop-blur transition hover:bg-white/10">Discover the club <ChevronRight size={16}/></Link></div></Reveal></div></div>
      <div className="relative mx-auto grid max-w-7xl grid-cols-2 gap-px overflow-hidden rounded-2xl border border-white/[.08] bg-white/[.08] md:grid-cols-4">{statRows.map(([n,l])=><div key={l} className="bg-black/55 px-6 py-6 backdrop-blur-xl"><p className="text-2xl font-medium">{n}</p><p className="mt-2 text-[10px] tracking-[.16em] text-white/35">{l.toUpperCase()}</p></div>)}</div>
    </section>
    <section className="mx-auto max-w-7xl px-6 py-28"><Reveal><SectionTitle eyebrow="LIVE SIGNAL" title="A calendar built for momentum." copy="Published events from the admin portal appear here automatically."/></Reveal>{events.length?<><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{events.map((e,i)=><Reveal key={e.slug} delay={i*.08}><EventCard event={e} index={i}/></Reveal>)}</div><Link href="/events" className="mt-7 inline-flex items-center gap-2 text-sm text-violet-300">View the complete calendar <ArrowUpRight size={15}/></Link></>:<EmptyState title="No public events yet." copy="Create and publish events from the admin portal. Until then, visitors will not see fake event data." href="/admin" action="Open admin"/>}</section>
    <section className="border-y border-white/[.06] bg-white/[.018]"><div className="mx-auto grid max-w-7xl gap-14 px-6 py-28 lg:grid-cols-[.9fr_1.1fr]"><Reveal><SectionTitle eyebrow="ONE SYSTEM / MANY DISCIPLINES" title="Teams controlled by admins." copy="Only teams added in the dashboard are shown here."/><Link className="inline-flex items-center gap-2 rounded-full border border-white/10 px-5 py-3 text-sm text-white/70" href="/teams">Explore the network <ArrowRight size={15}/></Link></Reveal><div className="grid gap-3 sm:grid-cols-2">{teams.length?teams.slice(0,6).map((team,i)=><Reveal key={team.id} delay={i*.04}><div className="edge group rounded-xl bg-black/25 p-5 transition hover:bg-violet-500/[.08]"><div className="flex justify-between"><Orbit size={18} className="text-violet-300"/><span className="text-xs text-white/25">{team.members}</span></div><h3 className="mt-7 text-sm">{team.name}</h3><p className="mt-2 text-xs leading-5 text-white/35">{team.description || "No description added yet."}</p></div></Reveal>):<EmptyState title="No teams published yet." copy="Add teams and assign members from the admin portal."/>}</div></div></section>
    {achievements.length || sponsors.length || gallery.length ? <section className="mx-auto max-w-7xl px-6 py-20"><div className="grid gap-4 md:grid-cols-3">{achievements.slice(0,3).map((item:any)=><div className="glass rounded-2xl p-6" key={item._id}><p className="text-[10px] tracking-[.2em] text-violet-300">{item.kind || "ACHIEVEMENT"}</p><p className="mt-4 text-lg">{item.title}</p><p className="mt-2 text-xs leading-5 text-white/40">{item.description}</p></div>)}</div></section> : null}
    <section className="mx-auto max-w-7xl px-6 py-28"><div className="relative overflow-hidden rounded-3xl border border-violet-300/15 bg-gradient-to-br from-violet-950/80 to-fuchsia-950/30 px-7 py-16 md:px-16"><Zap className="absolute -right-6 -top-8 h-52 w-52 text-white/[.035]"/><p className="text-[10px] tracking-[.3em] text-violet-200">ACCESS THE NETWORK</p><h2 className="mt-6 max-w-2xl text-4xl font-medium tracking-tight md:text-6xl">The future needs people who show up early.</h2><p className="mt-5 max-w-xl text-sm leading-7 text-white/50">Find your team, enter the room, and start making something that matters.</p><Link href="/contact" className="mt-8 inline-flex items-center gap-2 rounded-full bg-white px-6 py-3 text-sm font-semibold text-black">Connect with us <ArrowUpRight size={15}/></Link></div></section>
  </PublicShell>;
}
